language: node_js
node_js:
  - "6"
env:
  - NODE_ENV=production
cache:
  directories:
  - node_modules
install:
  - npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - npm run build
  - npm test
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master